### ISSUE TITLE
Add top-level await support for lambdas by default

### ISSUE THREAD

**Issue by adriencaccia** [swarmion/swarmion#237]
As shown in: https://dev.to/oieduardorabelo/top-level-await-in-aws-lamba-with-typescript-1bf0?utm_source=newsletter&utm_medium=email&utm_content=offbynone&utm_campaign=Off-by-none%3A%20Issue%20%23198

We can easily have top-level await support with the following `esbuild` config:

```yaml
format: "esm"
outputFileExtension: ".mjs"
platform: "node"
target: "esnext"
```

Adding it as a default will definitely be an improvement.
